config {
  type: "table"
}


js {

  function run() {
    if (fivetran_utils.enabled_vars([constants.hubspot_marketing_enabled, constants.hubspot_email_event_enabled, constants.hubspot_email_event_status_change_enabled]) == true ) {
      query =  `
        select * from ${constants.SOURCE_PROJECT}.${constants.SOURCE_DATASET}.email_event_status_change`
      return query
    }
    return ``
  }


}

${run()}